### ISSUE TITLE
make error: nvcc fatal   : 'arch=native': expected a number 

### ISSUE THREAD

**Issue by 644zhang** [extendedcaffe/extended-caffe#2]
Dear sir,
When I execute the command "make -j8 ", I meet the problem:
"NVCC src/caffe/util/bbox_util.cu
nvcc fatal   : 'arch=native': expected a number
Makefile:768: recipe for target '.build_release/cuda/src/caffe/util/bbox_util.o' failed
make: *** [.build_release/cuda/src/caffe/util/bbox_util.o] Error 1"

How can I solve this problem?

**Comment by 644zhang** [comment]
This is my Makefile.config:
[Makefile.zip](https://github.com/extendedcaffe/extended-caffe/files/1162148/Makefile.zip)

**Comment by raymon-tian** [comment]
@644zhang 
the command  `make -j `nproc`` is not used correctly.
just only `make` will work.
i.e. do not specify the number of the kernals.
